name: C# Build

on:
 push:
 branches:
  - master # Runs on every push to the main branch
  pull_request:
  branches:
   - main # Runs on every pull to request main

   jobs:
    build:
    runs-on: windows-latest # Use the lastest windows runner


    steps:
    -name: Checkout 
    uses: actions/checkout@v4 # Clones the Respository

    - name: Set up .NET
    uses: actions/setup-dotnet@v3

    with: 
    dotnet-version: '7.x'

    - name: Restore Depedencies
      runs: dotnet restore # Ensures dependencies are installed

      - name: Build the Project
        runs: dotnet build --no-restore --configuration Release # Builds your project
      

    
