name: C# Build

on:
  push:
    branches:
      - master # Runs on every push to the master branch
  pull_request:
    branches:
      - main # Runs on every pull request to the main branch

jobs:
  build:
    runs-on: windows-latest # Use the latest Windows runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Clones the repository

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '7.x'

      - name: Restore Dependencies
        run: dotnet restore # Ensures dependencies are installed

      - name: Build the Project
        run: dotnet build --no-restore --configuration Release # Builds your project
